# Generated by Django 4.1.7 on 2023-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.DateField()),
                ('modelo', models.CharField(max_length=100)),
                ('data_compra', models.DateField()),
            ],
        ),
    ]
