# Generated by Django 4.1.7 on 2023-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carro',
            name='id',
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
