# Generated by Django 4.1.7 on 2023-03-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_cliente_remove_carro_id_alter_carro_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_aluguel', models.DateField()),
                ('data_entrega', models.DateField()),
                ('devolucao', models.BooleanField(verbose_name='devolvido')),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aluguel.cliente')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aluguel.carro')),
            ],
        ),
    ]
